### ISSUE TITLE
Create webpage 

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Diabetes-Predictor#1]
## Create a webpage for the user to enter the inputs
> Create input fields: 
- Number of times pregnant
- Diastolic Blood Pressure
- Tricep skin fold thickness
- 2-Hour Serum insulin
- Body mass index
- Diabetes pedigree function
- Age

**Comment by Shivashish-rwt** [comment]
I can create a webpage. Please assign this to me.

**Comment by Nitesh-thapliyal** [comment]
@Shivashish-rwt great, assigning this to you!

**Comment by Shivashish-rwt** [comment]
Thanks!!
