### ISSUE TITLE
Integrate Diabetes model to the webpage

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Diabetes-Predictor#2]
Integrate the Diabetes  deep learning model to the webpage and display the output on the webpage

**Comment by gokhalevedant06** [comment]
Hi @Nitesh-thapliyal, I can do the integration as well as develop the web page. Please assign this issue to me

**Comment by Nitesh-thapliyal** [comment]
Hey @gokhalevedant06 webpage issue is already assigned , you can check that issue and can collaborate with him and can integrate the model later on

**Comment by gokhalevedant06** [comment]
Cool! Please assign this issue to me

**Comment by Nitesh-thapliyal** [comment]
> Cool! Please assign this issue to me

sure!

**Comment by Nitesh-thapliyal** [comment]
Hey, @gokhalevedant06 you can now work on integrating the model into the webpage and improve the look of the webpage.

**Comment by gokhalevedant06** [comment]
I was thinking to integrate using a flask server

**Comment by galahad42** [comment]
@Nitesh-thapliyal can you assign this issue to me. I can work on the frontend part of the webpage

**Comment by Nitesh-thapliyal** [comment]
@galahad42 sure, you can improve the frontend, Assigning this issue to you

**Comment by gokhalevedant06** [comment]
@Nitesh-thapliyal I have already solved this issue. Could you please review my PR
